// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateItemItemPostData, CreateItemItemPostErrors, CreateItemItemPostResponses, GetItemByIdItemIdGetData, GetItemByIdItemIdGetErrors, GetItemByIdItemIdGetResponses, GetMeUserMeGetData, GetMeUserMeGetResponses, GetUserByIdUserIdGetData, GetUserByIdUserIdGetErrors, GetUserByIdUserIdGetResponses, GetUsersItemsUserIdItemsGetData, GetUsersItemsUserIdItemsGetErrors, GetUsersItemsUserIdItemsGetResponses, LoginAccessTokenLoginAccessTokenPostData, LoginAccessTokenLoginAccessTokenPostErrors, LoginAccessTokenLoginAccessTokenPostResponses, NewUserUserPostData, NewUserUserPostErrors, NewUserUserPostResponses, UpdateBioUserPutData, UpdateBioUserPutErrors, UpdateBioUserPutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginAccessTokenLoginAccessTokenPost = <ThrowOnError extends boolean = false>(options: Options<LoginAccessTokenLoginAccessTokenPostData, ThrowOnError>): RequestResult<LoginAccessTokenLoginAccessTokenPostResponses, LoginAccessTokenLoginAccessTokenPostErrors, ThrowOnError> => (options.client ?? client).post<LoginAccessTokenLoginAccessTokenPostResponses, LoginAccessTokenLoginAccessTokenPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/login/access-token',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Get Me
 */
export const getMeUserMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeUserMeGetData, ThrowOnError>): RequestResult<GetMeUserMeGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetMeUserMeGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/me',
    ...options
});

/**
 * Get User By Id
 */
export const getUserByIdUserIdGet = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdUserIdGetData, ThrowOnError>): RequestResult<GetUserByIdUserIdGetResponses, GetUserByIdUserIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetUserByIdUserIdGetResponses, GetUserByIdUserIdGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/user/{id}',
    ...options
});

/**
 * New User
 */
export const newUserUserPost = <ThrowOnError extends boolean = false>(options: Options<NewUserUserPostData, ThrowOnError>): RequestResult<NewUserUserPostResponses, NewUserUserPostErrors, ThrowOnError> => (options.client ?? client).post<NewUserUserPostResponses, NewUserUserPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Bio
 */
export const updateBioUserPut = <ThrowOnError extends boolean = false>(options: Options<UpdateBioUserPutData, ThrowOnError>): RequestResult<UpdateBioUserPutResponses, UpdateBioUserPutErrors, ThrowOnError> => (options.client ?? client).put<UpdateBioUserPutResponses, UpdateBioUserPutErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Users Items
 */
export const getUsersItemsUserIdItemsGet = <ThrowOnError extends boolean = false>(options: Options<GetUsersItemsUserIdItemsGetData, ThrowOnError>): RequestResult<GetUsersItemsUserIdItemsGetResponses, GetUsersItemsUserIdItemsGetErrors, ThrowOnError> => (options.client ?? client).get<GetUsersItemsUserIdItemsGetResponses, GetUsersItemsUserIdItemsGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/user/{id}/items/',
    ...options
});

/**
 * Create Item
 */
export const createItemItemPost = <ThrowOnError extends boolean = false>(options: Options<CreateItemItemPostData, ThrowOnError>): RequestResult<CreateItemItemPostResponses, CreateItemItemPostErrors, ThrowOnError> => (options.client ?? client).post<CreateItemItemPostResponses, CreateItemItemPostErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/item/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Item By Id
 */
export const getItemByIdItemIdGet = <ThrowOnError extends boolean = false>(options: Options<GetItemByIdItemIdGetData, ThrowOnError>): RequestResult<GetItemByIdItemIdGetResponses, GetItemByIdItemIdGetErrors, ThrowOnError> => (options.client ?? client).get<GetItemByIdItemIdGetResponses, GetItemByIdItemIdGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/item/{id}',
    ...options
});
