// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Body_login_access_token_login_access_token_post
 */
export type BodyLoginAccessTokenLoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Item
 */
export type Item = {
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Author Id
     */
    author_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Text
     */
    text: string;
};

/**
 * ItemsOut
 */
export type ItemsOut = {
    /**
     * Data
     */
    data: Array<Item>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Plain Pwd
     */
    plain_pwd: string;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Name
     */
    name: string;
    /**
     * Bio
     */
    bio: string;
};

/**
 * UserUpdateBio
 */
export type UserUpdateBio = {
    /**
     * New Bio
     */
    new_bio: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginAccessTokenLoginAccessTokenPostData = {
    body: BodyLoginAccessTokenLoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/login/access-token';
};

export type LoginAccessTokenLoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenLoginAccessTokenPostError = LoginAccessTokenLoginAccessTokenPostErrors[keyof LoginAccessTokenLoginAccessTokenPostErrors];

export type LoginAccessTokenLoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenLoginAccessTokenPostResponse = LoginAccessTokenLoginAccessTokenPostResponses[keyof LoginAccessTokenLoginAccessTokenPostResponses];

export type GetMeUserMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type GetMeUserMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type GetMeUserMeGetResponse = GetMeUserMeGetResponses[keyof GetMeUserMeGetResponses];

export type GetUserByIdUserIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type GetUserByIdUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdUserIdGetError = GetUserByIdUserIdGetErrors[keyof GetUserByIdUserIdGetErrors];

export type GetUserByIdUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type GetUserByIdUserIdGetResponse = GetUserByIdUserIdGetResponses[keyof GetUserByIdUserIdGetResponses];

export type NewUserUserPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/user/';
};

export type NewUserUserPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewUserUserPostError = NewUserUserPostErrors[keyof NewUserUserPostErrors];

export type NewUserUserPostResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type NewUserUserPostResponse = NewUserUserPostResponses[keyof NewUserUserPostResponses];

export type UpdateBioUserPutData = {
    body: UserUpdateBio;
    path?: never;
    query?: never;
    url: '/user/';
};

export type UpdateBioUserPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateBioUserPutError = UpdateBioUserPutErrors[keyof UpdateBioUserPutErrors];

export type UpdateBioUserPutResponses = {
    /**
     * Successful Response
     */
    200: UserOut;
};

export type UpdateBioUserPutResponse = UpdateBioUserPutResponses[keyof UpdateBioUserPutResponses];

export type GetUsersItemsUserIdItemsGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/user/{id}/items/';
};

export type GetUsersItemsUserIdItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersItemsUserIdItemsGetError = GetUsersItemsUserIdItemsGetErrors[keyof GetUsersItemsUserIdItemsGetErrors];

export type GetUsersItemsUserIdItemsGetResponses = {
    /**
     * Successful Response
     */
    200: ItemsOut;
};

export type GetUsersItemsUserIdItemsGetResponse = GetUsersItemsUserIdItemsGetResponses[keyof GetUsersItemsUserIdItemsGetResponses];

export type CreateItemItemPostData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/item/';
};

export type CreateItemItemPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemItemPostError = CreateItemItemPostErrors[keyof CreateItemItemPostErrors];

export type CreateItemItemPostResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type CreateItemItemPostResponse = CreateItemItemPostResponses[keyof CreateItemItemPostResponses];

export type GetItemByIdItemIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/item/{id}';
};

export type GetItemByIdItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetItemByIdItemIdGetError = GetItemByIdItemIdGetErrors[keyof GetItemByIdItemIdGetErrors];

export type GetItemByIdItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: Item;
};

export type GetItemByIdItemIdGetResponse = GetItemByIdItemIdGetResponses[keyof GetItemByIdItemIdGetResponses];
